Stages/2025: Introduce Fortran flags to prevent errors
- `-fallow-argument-mismatch`

Rank and type mismatch errors.

Example:
```
Error: Rank mismatch between actual argument at (1) and actual
argument at (2) (rank-1 and scalar)
```

- `-fallow-invalid-boz`

```
Error: BOZ literal constant at (1) is neither a data-stmt-constant nor
an actual argument to INT, REAL, DBLE, or CMPLX intrinsic function
[see ‘-fno-allow-invalid-boz’]
```